on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
        env:
        	    CI: false

        - name: List output files
        	  run: find build-web/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: '${{ secrets.FTP_ADDRESS }}'
        username: '${{ secrets.FTP_USER }}'
        password: '${{ secrets.FTP_PASSWORD }}'
        local-dir: build-web/
        server-dir: /domains/lavrentiev.tech/public_html
